import json
from pathlib import Path
from warroom_setup import persona_sync
from warroom_setup.agent_model import AgentIdentity

IDENT = AgentIdentity(
    agent_name="aria", handle="aria-sh", display_name="Aria",
    model="opus", specialist_prefix="aria", agent_fingerprint="aria-xyz",
)


def _fixture(tmp_path):
    (tmp_path / "persona").mkdir()
    (tmp_path / "templates").mkdir()
    (tmp_path / "persona" / "voice.md").write_text(
        "---\ntype: identity\n---\n# Voice\n\nI am {{display_name}}.\n\n## Related\n- [[role]]\n")
    (tmp_path / "templates" / "soul-preamble.md").write_text(
        "# {{display_name}} - Persona\n\nfingerprint {{agent_fingerprint}}")
    manifest = {
        "header": "<!-- DO NOT EDIT. Generated by persona_sync.py for {{handle}} -->",
        "outputs": [
            {"name": "soul", "target": str(tmp_path / "out" / "{{handle}}" / "SOUL.md"),
             "preamble": "templates/soul-preamble.md", "trailer": "",
             "sections": [{"title": "Voice", "source": "persona/voice.md"}]},
        ],
    }
    (tmp_path / "manifest.json").write_text(json.dumps(manifest))
    return tmp_path


def test_strip_frontmatter_and_h1():
    assert persona_sync.strip_frontmatter_and_h1("---\na: 1\n---\n# Title\n\nbody") == "body"


def test_strip_frontmatter_unclosed_raises():
    import pytest
    with pytest.raises(ValueError):
        persona_sync.strip_frontmatter_and_h1("---\nno close\n")


def test_strip_related_removes_footer_until_next_h2():
    txt = "body\n\n## Related\n- [[x]]\n\n## Keep\nkept"
    assert persona_sync.strip_related(txt) == "body\n\n## Keep\nkept"


def test_render_writes_with_substitution(tmp_path):
    root = _fixture(tmp_path)
    rc = persona_sync.run(root / "manifest.json", root, IDENT, check=False)
    assert rc == 0
    out = (root / "out" / "aria-sh" / "SOUL.md").read_text()
    assert "# Aria - Persona" in out          # {{display_name}} substituted in preamble
    assert "fingerprint aria-xyz" in out
    assert "## Voice" in out                   # title from manifest, not file H1
    assert "I am Aria." in out                 # {{display_name}} substituted in body
    assert "## Related" not in out             # footer stripped
    assert "{{" not in out                     # no unsubstituted placeholders
    assert out.endswith("\n")


def test_check_reports_drift_without_writing(tmp_path):
    root = _fixture(tmp_path)
    target = root / "out" / "aria-sh" / "SOUL.md"
    target.parent.mkdir(parents=True)
    target.write_text("stale\n")
    rc = persona_sync.run(root / "manifest.json", root, IDENT, check=True)
    assert rc == 1
    assert target.read_text() == "stale\n"     # never written in check mode


def test_shipped_manifest_compiles_against_seeded_overlay(tmp_path, monkeypatch):
    # Redirect ~ to tmp_path so the manifest's "~/.hermes" and "~/.claude"
    # targets (resolved via os.path.expanduser in persona_sync.run) land in the
    # sandbox instead of the developer's real home.
    monkeypatch.setenv("HOME", str(tmp_path))
    # Simulate an installed profile: copy persona/ -> local/persona/, then compile.
    import shutil
    src = Path(__file__).resolve().parents[1]
    prof = tmp_path / "prof"
    for d in ("persona", "templates", "shared"):
        shutil.copytree(src / d, prof / d)
    shutil.copy2(src / "manifest.json", prof / "manifest.json")
    (prof / "local").mkdir()
    shutil.copytree(prof / "persona", prof / "local" / "persona")
    rc = persona_sync.run(prof / "manifest.json", prof, IDENT, check=False)
    assert rc == 0
    soul = (Path.home() / ".hermes" / "profiles" / "aria-sh" / "SOUL.md")
    head = (Path.home() / ".claude" / "agents" / "aria.md")
    assert soul.is_file() and head.is_file()
    assert "{{" not in soul.read_text() and "{{" not in head.read_text()
    assert "## Voice" in soul.read_text()
